version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    networks:
      - backnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d example -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - frontnet
    depends_on:
      db:
        condition: service_healthy

  proxy:
    build:
      context: ./proxy
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

secrets:
  db-password:
    file: ./db/password.txt

networks:
  frontnet:
  backnet:
